### ISSUE TITLE
spivdiia.org.ua

### ISSUE THREAD

**Issue by Skrriply** [braveinnovators/ukrainian-security-filter#32]
**Describe the bug**
Blocking a legitimate website.
SpivDiia is a charitable foundation

**To Reproduce**
1. Go to 'https://spivdiia.org.ua/'
2. See error

**Expected behavior**
Opening a website

**Screenshots**
![fond](https://github.com/user-attachments/assets/222d44ab-26ce-4dfd-863f-b2a1c6603358)

**Smartphone:**
 - Device: Realme 6
 - OS: Android 11
 - Browser: FireFox
 - Version 128.0.3

**Additional context**
Blocklist version: 20240805.1 (24.08.1)

**Comment by myroslavandriychuk** [comment]
@serhiyguryev щойно перевірив цей домен, можемо його додавати до виключень (зараз це зроблю).

**Comment by myroslavandriychuk** [comment]
Тепер все має бути ок pull request #33
